#默认使用配置
spring:
  profiles:
    active: test

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.hnu.elvis.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://localhost:3306/jewels?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver